language: node_js

node_js:
  - "8.9.1"

branches:
  only:
  - master
  - /^feature\/.*$/

before_install:
  - npm i -g npm@6.9.0

install:
- npm install

script:
- npm run build
- npm run lint
- npm run test
