language: node_js

node_js:
  - "8.9.1"

branches:
  only:
  - master
  - /^feature\/.*$/

before_install:
  - npm i -g npm@6.9.0

install:
- npm ci

script:
- npm run build:prod
- npm run lint
- npm version 1.0.7

script: echo "Running tests against $(node -v)..."
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

deploy:
  provider: npm
  email: "alenkaru96@gmail.com"
  api_key: $npm_token
  skip_cleanup: true
  on:
     branches:
          only:
            - master
